"""Patches the AndroidManifest.xml generated by `flutter create`:
  * adds permissions for the foreground service, notifications and ads
  * injects the AdMob application-id meta-data (Google TEST app id)

Usage: python3 patch_manifest.py path/to/AndroidManifest.xml
"""
import re
import sys

PERMISSIONS = [
    "android.permission.FOREGROUND_SERVICE",
    "android.permission.FOREGROUND_SERVICE_SPECIAL_USE",
    "android.permission.POST_NOTIFICATIONS",
    "android.permission.WAKE_LOCK",
    "android.permission.RECEIVE_BOOT_COMPLETED",
    "android.permission.INTERNET",
    "android.permission.ACCESS_NETWORK_STATE",
]

# Google's official TEST AdMob application id. Replace with your real id
# (ca-app-pub-XXXX~YYYY) from the AdMob console before publishing.
ADMOB_APP_ID = "ca-app-pub-3940256099942544~3347511713"
ADMOB_META = (
    '<meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" '
    f'android:value="{ADMOB_APP_ID}"/>'
)


def main():
    path = sys.argv[1]
    with open(path, "r", encoding="utf-8") as f:
        content = f.read()

    for perm in PERMISSIONS:
        if perm not in content:
            tag = f'<uses-permission android:name="{perm}"/>'
            content = re.sub(r"(<manifest[^>]*>)", r"\1\n    " + tag, content, count=1)

    if "com.google.android.gms.ads.APPLICATION_ID" not in content:
        # Insert the meta-data just inside the <application> opening tag.
        content = re.sub(
            r"(<application[^>]*>)", r"\1\n        " + ADMOB_META, content, count=1
        )

    with open(path, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"Patched {path} with permissions and AdMob app id.")


if __name__ == "__main__":
    main()
