"""Patches the AndroidManifest.xml generated by `flutter create`:
  * adds the permissions the foreground service + notifications need
  * declares the flutter_background_service foreground service as
    foregroundServiceType="specialUse" (REQUIRED on Android 14+, or starting
    the service crashes the app) and matches it to the SPECIAL_USE permission.

Usage: python3 patch_manifest.py path/to/AndroidManifest.xml
"""
import re
import sys

PERMISSIONS = [
    "android.permission.FOREGROUND_SERVICE",
    "android.permission.FOREGROUND_SERVICE_SPECIAL_USE",
    "android.permission.POST_NOTIFICATIONS",
    "android.permission.WAKE_LOCK",
    "android.permission.RECEIVE_BOOT_COMPLETED",
]

# Override the plugin's service so its foreground-service type is one we hold a
# permission for. tools:replace makes the manifest merger use our value.
SERVICE_OVERRIDE = (
    '<service\n'
    '            android:name="id.flutter.flutter_background_service.BackgroundService"\n'
    '            android:foregroundServiceType="specialUse"\n'
    '            android:exported="false"\n'
    '            tools:replace="android:foregroundServiceType">\n'
    '            <property\n'
    '                android:name="android.app.PROPERTY_SPECIAL_USE_FGS_SUBTYPE"\n'
    '                android:value="User-configured battery-level alarm that must observe charge state continuously" />\n'
    '        </service>'
)


def main():
    path = sys.argv[1]
    s = open(path, encoding="utf-8").read()

    # Ensure the tools namespace exists (needed for tools:replace).
    if "xmlns:tools" not in s:
        s = re.sub(
            r"(<manifest\b)",
            lambda m: m.group(1) + ' xmlns:tools="http://schemas.android.com/tools"',
            s,
            count=1,
        )

    # Add permissions.
    for perm in PERMISSIONS:
        if perm not in s:
            tag = f'<uses-permission android:name="{perm}"/>'
            s = re.sub(
                r"(<manifest[^>]*>)",
                lambda m, t=tag: m.group(1) + "\n    " + t,
                s,
                count=1,
            )

    # Add the foreground-service type override inside <application>.
    if "id.flutter.flutter_background_service.BackgroundService" not in s:
        s = re.sub(
            r"(<application[^>]*>)",
            lambda m: m.group(1) + "\n        " + SERVICE_OVERRIDE,
            s,
            count=1,
        )

    open(path, "w", encoding="utf-8").write(s)
    print(f"Patched {path}: permissions + specialUse FGS type.")


if __name__ == "__main__":
    main()
